### ISSUE TITLE
Platform Support for Darwin x64

### ISSUE THREAD

**Issue by idkjs** [utkarshkukreti/reaml#3]
I havent had any luck with any of your fine work today!

```sh
dependencies:
+ bs-webapi 0.15.6

devDependencies:
+ @glennsl/bs-jest 0.4.9
+ bs-platform 7.0.1
+ highlight.js 9.18.0
+ jest 25.1.0
+ npm-run-all 4.1.5
+ parcel-bundler 1.12.4
+ preact 10.2.1
+ react 16.12.0
+ react-dom 16.12.0
+ rimraf 3.0.1

> reaml@0.7.2 postinstall /Users/prisc_000/Downloads/reaml
> cd ppx && node copy.js

reaml_ppx does not support this platform :(
reaml_ppx comes prepacked as built binaries to avoid large
dependencies at build-time.

If you want reaml_ppx to support this platform natively,
please open an issue at our repository, linked above. Please
specify that you are on the darwin platform,');
on the x64 architecture.

 ERROR  Command failed with exit code 1.
➜  reaml [master*]
```

Thanks for sharing.

**Comment by utkarshkukreti** [comment]
I should mention this somewhere - to work on this repo directly, you need to first install `esy` and do `cd ppx && make`. Then do `yarn install && yarn build` from root.

I'd suggest you play with https://github.com/utkarshkukreti/reaml-starter which should work with just `yarn install`. Let me know how that goes!

**Comment by idkjs** [comment]
Already tried the starter. No luck. Will get you an error and post it there.

Ran the command you suggest here. You get error for `cssnano` and `scheduler`. After `pnpm install -D cssnano scheduler` and re-running `pnpm build && pnpm start:parcel` you get a successful build. Maybe add those as deps or peer deps. Thanks for the assistance.
