### ISSUE TITLE
Usage of JSX

### ISSUE THREAD

**Issue by arecvlohe** [utkarshkukreti/reaml#6]
First off, thanks for this library! I am using it in a side project and I am really enjoying it.

I have just two questions and not a feature request. 

I have gotten used to the syntax which reminds me a lot of Elm and their HTML templating. I was curious, since JSX is built into ReasonML directly, could it be used as an alternate syntax in this library?

I also was wondering if I could convert your other examples into ReasonML? The syntax for OCaml always trips me up and it may also trip up newcomers. I am down to help in this area if contributions are welcome.

Thanks again! I appreciate all the effort you have put into this.

**Comment by utkarshkukreti** [comment]
> First off, thanks for this library! I am using it in a side project and I am really enjoying it.

Thanks :)

> I have gotten used to the syntax which reminds me a lot of Elm and their HTML templating. I was curious, since JSX is built into ReasonML directly, could it be used as an alternate syntax in this library?

JSX in ReasonML compiles to what is described [here](https://reasonml.github.io/docs/en/jsx). If you create correct wrappers for all Reaml functions, it should be possible. Another way is to write a separate ppx like [this one](https://github.com/osener/ppx-tea-jsx) does for `bucklescript-tea`. I do not plan to do either of those as I like how composable this Elm style API is.

> I also was wondering if I could convert your other examples into ReasonML? The syntax for OCaml always trips me up and it may also trip up newcomers. I am down to help in this area if contributions are welcome.

Manual conversion of every example is probably not good for long term maintenance (I plan to add more examples over time). Have you tried using `bsrefmt` to convert the OCaml examples into ReasonML? The code is not perfectly idiomatic but it's good enough to start. Here's how you can do it from within this repository:

    $ npm run bsrefmt examples/Clicks.ml

    or

    $ yarn bsrefmt examples/Clicks.ml

Maybe I should include this auto converted code in the examples website. What do you think about that? Would that help?

**Comment by arecvlohe** [comment]
I have wanted to write something earlier but I have been going back and forth on the usage of BuckleScript/ReasonML and if I want to continue using it for FD development. With the recent syntax changes and the closed-mindedness to more FP centric ideas I think it's best to keep things in the OCaml syntax using functions. Disregard what I said before about JSX!
